---
title: 'How to process information gathered on your mobile to get information on everyday exposure to greenspace?'
author: ~
date: '2019-06-02'
draft: yes
slug: everydaygreen
tags: ["GPS", "Iphone","Arc App","Green space","Natural environment"]
categories: ["Data Analysis"]
---

## Background

Spending time in the natural environment (green and blue spaces) is linked with better health outcomes throughout life. From prenatal/pregnancy, childhood, adolescence to adulthood and later adulthood, we benefit from being in these places. Briefly they provide opportunities for more social interactions and physical activity, a restoration in our attention, a reduction in stress and a more diverse microbial exposure [(Douglas, 2017)](https://researchrepository.ucd.ie/handle/10197/8515). Greater access and use of greenspace may reduce health inequalities - it may be [**equigenic**](https://cresh.org.uk/2013/11/08/what-is-equigenesis-and-how-might-it-help-narrow-health-inequalities/). 

So the main question is: how do we plan, design and manage greenspaces so that they generate the benefits to those most in need?

To answer this question we need to know the patterns of use. In doing so we  



We can think of this on a everyday or a lifecourse level. In this blog post I'm going to concentrate on the former. We often assume that people tend to spend most of their time the parks closest to their homes, however, at least in 10/11 year olds this is not always the case [(Olsen, 2019)](http://eprints.gla.ac.uk/178909/1/178909.pdf).

Everday interations with greenspace can be classified by whether they are passive or active (ref), with active interactions showing most benefit for 


After thousands of publications on the subject we still have little understanding of the ways in which these spaces are being used in daily life. We have assumed that we spend more time in parks that are closer to us, but is this the case? 




  