---
title: 'How to quickly visualise massive spatio-temporal data?'
author: ~
date: '2018-12-22'
draft: no
slug: kepler
tags: ["Movement","Natural environment","Greenspace", "Arc app", "GPS", "UGCP", "Activity Space"]
categories: ["Data Visualisation"]
---

## Background
Are you collecting lots of geospatial data and need a way to quickly visualise what you've got? Read on!

I had this problem; I was collecting a lot of information on my daily movements from [Arc App: Location and Activity](https://itunes.apple.com/us/app/arc-app-location-activity/id1063151918?mt=8) (more on the use of Arc for research later). Additionally, I wanted to quickly see what features of the urban environment (e.g. greenspaces) I was being 'exposed' to. The solution was Uber's open source geospatial analysis tool: [Kepler.gl](https://kepler.gl). Some formatting of your data is required, but it's pretty simple, just output a CSV with a [datetime](https://stat.ethz.ch/R-manual/R-devel/library/base/html/as.POSIXlt.html), latitude and longitude column, alongside any other attribute data that you are interested in (here I'm interested in greenspace exposure, i.e. when I was within 50 metres of a [greenspace](https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-greenspace.html)). That's the hard bit. After this, you have lots of options for styling your visualisation and this generally pretty easy to work through. You receive an automatic animation of your data over time, which you have control of with a set of buttons to determine playback. A notable, but more time-consuming, alternative to creating animations from data is the [QGIS Time manager](https://medium.com/@tjukanov/geogiffery-in-a-nutshell-introduction-to-qgis-time-manager-31bb79f2af19).  
Once you like the look of your visualisation, there are options to share as an image or a URL. If, like me, you want to do furthering editing (e.g. annotate certain frames) then you can do a screen recording and then import to a video editing program such as iMovie (n.b. There is probably a better way of doing this). Anyway, hopefully this blog will give enough information to get started with kepler.gl. I was able to create a visualisation of my contact with greenspaces over a 6 months period, which is shown below.

## Visualisation 
```{r echo=FALSE}
blogdown::shortcode("youtube", "5K49kbiK-Q0")
```



  
