---
title: 'How to make teaching/outreach more interactive? Experiences with Mentimeter'
author: ~
date: '2018-11-03'
draft: no
slug: mentimeter
tags: ["Mentimeter","Interactive Polling", "Teaching","Outreach", "Workshop", "Pedagogy", "Technology", "Powerpoint"]
categories: ["Teaching Tips"]
---

## Background
I am keen to employ technology to assist in teaching. I went to the [Social Science and Medicine Annual Scientific meeting](https://socsocmed.org.uk/annual-scientific-meeting/) in Glasgow, last September and noticed that they were using software to get responses from the audience. The software was called [Mentimeter](https://www.mentimeter.com/). I did some investigating and set out a plan on using it for upcoming teaching and outreach. It turns out there has been a paper published from researchers from the University of Glasgow on the merits of interactive polling for teaching, see [here](http://evs.psy.gla.ac.uk/papers/draperbrown.pdf). The authors summarise that experiences of this technology are generally positive but caution that future use should focus first on the pedagogical approach. Two approaches are put forward: one, launching student discussion, and two to focus on developing teaching aligned to the students questions and needs. I'll now give a brief description on how to carry out a Mentimeter polling session and how I have used it in teaching and outreach.     

## Mentimeter
Mentimeter is proprietary cloud-based software that can collect, record and visualise participant responses via interaction with a webpage. The teacher first asks the students to go onto the webpage and input a code to get to the right question (questions are created on the Mentimeter site, which is very intuitive). The teacher then activates the voting and results are visualised in real-time on the screen. I've found that the easiest way to include this in presentations is to use the Powerpoint [plugin](https://www.mentimeter.com/powerpoint). The plots and data can then be downloaded and are useful for reports and modifying future material.

## Examples of use
1. Teaching: Honing in on plans for dissertations by asking what type of data students anticipate collecting, to stimulate discussion on the merits of these data.
2. Outreach: Developing a structural equation model by asking experts to categorise pathways by their strength of association with outcomes 

## Thoughts on use
1. The use of an internet-enabled device can be exclusionary, if possible there should be devices that can be used by students that are ready to vote. 
2. In addition to the previous point, it might be beneficial to mix more traditional interactive methods (e.g. the Carousel Activity) with the new technology so there's a greater chance that people feel comfortable with the type of interaction. 
3. The data and plots generated from interactive polling are so useful for reflection and it much less time consuming that transcribing hand written notes. 
4. There may be limitations to the type of questions that can be asked and the type of answers that can be supplied (e.g. doodles). In relation to the first point, especially in small groups with questions that might be more personal (i.e. related to their project) some students might not feel confident having their answers shared among the group, and this should be respected. 
5. Although I have found the technology to be robust, there are always going to be challenges with connectivity. The polling should be a pivot point not the key part of the teaching. 
6. I would think that spending more time on getting everyone up to speed with the concept of polling and having fewer key questions is better than trying to fit in lots of questions (also relates to student [respondent fatigue](https://www.google.com/search?q=response+fatigue&oq=response+fatigue&aqs=chrome..69i57j0l5.2592j0j4&sourceid=chrome&ie=UTF-8)).


What are your experiences with interactive polling for teaching/outreach?







